/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAvailabilityRouteImport } from './routes/_app.availability'
import { Route as AppManageRouteImport } from './routes/_app.manage'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppSystemRouteImport } from './routes/_app.system'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AppAvailabilityRoute
  '/manage': typeof AppManageRoute
  '/notices': typeof AppNoticesRoute
  '/system': typeof AppSystemRoute
  '/timeline': typeof AppTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AppAvailabilityRoute
  '/manage': typeof AppManageRoute
  '/notices': typeof AppNoticesRoute
  '/system': typeof AppSystemRoute
  '/timeline': typeof AppTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/availability': typeof AppAvailabilityRoute
  '/_app/manage': typeof AppManageRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/timeline': typeof AppTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/availability' | '/manage' | '/notices' | '/system' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/availability' | '/manage' | '/notices' | '/system' | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/availability'
    | '/_app/manage'
    | '/_app/notices'
    | '/_app/system'
    | '/_app/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/availability': {
      id: '/_app/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppManageRoute: typeof AppManageRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppSystemRoute: typeof AppSystemRoute
  AppTimelineRoute: typeof AppTimelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppManageRoute: AppManageRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppSystemRoute: AppSystemRoute,
  AppTimelineRoute: AppTimelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
