/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAvailabilityRouteImport } from './routes/_app.availability'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppManageRouteImport } from './routes/_app.manage'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSystemRouteImport } from './routes/_app.system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AppAvailabilityRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/manage': typeof AppManageRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AppAvailabilityRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/manage': typeof AppManageRoute
  '/settings': typeof AppSettingsRoute
  '/system': typeof AppSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/availability': typeof AppAvailabilityRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/manage': typeof AppManageRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/system': typeof AppSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/calendar'
    | '/chat'
    | '/manage'
    | '/settings'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/calendar'
    | '/chat'
    | '/manage'
    | '/settings'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/availability'
    | '/_app/calendar'
    | '/_app/chat'
    | '/_app/manage'
    | '/_app/settings'
    | '/_app/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/availability': {
      id: '/_app/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppManageRoute: typeof AppManageRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSystemRoute: typeof AppSystemRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppManageRoute: AppManageRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSystemRoute: AppSystemRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
